language: node_js
node_js:
  - "8.11"
  - "9.9"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - yarn lint
  # - yarn test:check-coverage
after_script:
  # - yarn report-coverage
before_install:
  - cd backend
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH
