language: node_js
node_js:
  - "8.10"
  - "9.9"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - yarn test:check-coverage
after_script:
  - yarn report-coverage
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
